services:
  - type: web
    name: isa-backend
    env: python
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: ./start.sh
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.6
      - key: GOOGLE_API_KEY
        sync: false
      - key: DEEPSEEK_API_KEY
        sync: false
